### ISSUE TITLE
stage1效果问题

### ISSUE THREAD

**Issue by tpzou** [fumyou13/LDBE#1]
你好，我下载了你的source-only的预训练模型，并采用‘ld’进行训练，同时对代码进行了一些调整，但发现训练结果（mIoU 41.04%）无法达到论文汇报的性能，想请教一下原因。

**Comment by fumyou13** [comment]
We have replied by gamil. Please check it.

**Comment by tpzou** [comment]
@fumyou13 Thanks for your quick reply!

I am sorry for sending the wrong "trainer.py" file earlier.  The new file has been sent to your gmail. To save time, I made minor adjustments compared to the original file. But the results are unsatisfactory and really confused me.

Looking forward to your reply.

**Comment by fumyou13** [comment]
We have replied by e-mail and fixed some bugs. Feel free to re-open the issue if you have any problem

**Comment by Jo-wang** [comment]
> We have replied by e-mail and fixed some bugs. Feel free to re-open the issue if you have any problem

Same issue here. Just wondering if you've updated the new version with bug-free code on github?

Thanks.
