### ISSUE TITLE
stage1结果精度问题

### ISSUE THREAD

**Issue by spicyduck** [fumyou13/LDBE#2]
您好，我在复现您第一阶段的代码过程中，在使用您给的预训练模型后，发现得到的mIoU只有41.2%，达不到45，想请教下原因，谢谢~

**Comment by Jo-wang** [comment]
> 您好，我在复现您第一阶段的代码过程中，在使用您给的预训练模型后，发现得到的mIoU只有41.2%，达不到45，想请教下原因，谢谢~

hi,你好，请问你有在stage0出现Resnet object is not iterable的情况吗？ 我遇到了这个问题。谢谢

**Comment by fumyou13** [comment]
Sorry for the late reply. 
ldbe_trainer.py line 123: if self.config.method == 'simsfss': -> if self.config.method == 'ld':
