### ISSUE TITLE
Unable to Reproduce the LD Performance 

### ISSUE THREAD

**Issue by luoxin13** [fumyou13/LDBE#3]
Hello, I found that the codes in run.py:L19-L25 have fixed the random seeds. In this way, the training results of the same config are supposed to be consistent among different running experiments. However, during experiments, I found LD could not reach the 45.5% mIoU. Instead, it reported the results as:

 ```
[0.4074220657348633, 0.4311172068119049, 0.4302009344100952, 0.42955252528190613, 0.42495307326316833, 0.4027584195137024, 0.40802302956581116, 0.38000842928886414, 0.38050565123558044]
```

 I am wondering if there exists any modification that affect the results?

**Comment by fumyou13** [comment]
Please check it:
ldbe_trainer.py line 123: if self.config.method == 'simsfss': -> if self.config.method == 'ld':

**Comment by Thebodyoflake** [comment]
I can't reproduce the results either. I could only reach 43.3% mIoU.
